/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ANNTreeDaemon_constants.h"

namespace ANNTreeDaemon {

const ANNTreeDaemonConstants g_ANNTreeDaemon_constants;

ANNTreeDaemonConstants::ANNTreeDaemonConstants() {
}

} // namespace

