/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ANNTreeDaemon_CONSTANTS_H
#define ANNTreeDaemon_CONSTANTS_H

#include "ANNTreeDaemon_types.h"

namespace ANNTreeDaemon {

class ANNTreeDaemonConstants {
 public:
  ANNTreeDaemonConstants();

};

extern const ANNTreeDaemonConstants g_ANNTreeDaemon_constants;

} // namespace

#endif
