// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ImageDaemon.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ImageDaemon;

class ImageDaemonHandler : virtual public ImageDaemonIf {
 public:
  ImageDaemonHandler() {
    // Your initialization goes here
  }

  void getBoWFeature(std::vector<Bin> & _return, const int64_t rowKey) {
    // Your implementation goes here
    printf("getBoWFeature\n");
  }

  void computeColorFeature(const int64_t rowKey) {
    // Your implementation goes here
    printf("computeColorFeature\n");
  }

  void query(std::vector<std::string> & _return, const std::string& imagePath) {
    // Your implementation goes here
    printf("query\n");
  }

  void addImage(const std::string& imageHash, const int64_t rowKey) {
    // Your implementation goes here
    printf("addImage\n");
  }

  void indexImage(const std::string& imageHash, const int64_t rowKey) {
    // Your implementation goes here
    printf("indexImage\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ImageDaemonHandler> handler(new ImageDaemonHandler());
  shared_ptr<TProcessor> processor(new ImageDaemonProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

