/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageDaemon_CONSTANTS_H
#define ImageDaemon_CONSTANTS_H

#include "ImageDaemon_types.h"

namespace net { namespace walnutvision {

class ImageDaemonConstants {
 public:
  ImageDaemonConstants();

};

extern const ImageDaemonConstants g_ImageDaemon_constants;

}} // namespace

#endif
